on:
  issue_comment:
    types: [created, edited]

jobs:
  comment:
    # PRコメントであり且つ /comment で始まるときのみ動作させる
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/comment')
    runs-on: ubuntu-latest

    steps:
      - name: Verify environment
        id: verify-environment
        uses: actions/github-script@v5
        with:
          script: |
            const allowed_environment_list = ['X', 'Y', 'Z']

            const comment = github.event.comment.body.split(' ')

            if (comment.length === 2 && allowed_environment_list.includes(comment[1])) {
                return comment[1]
            }

            const allowed_environment = allowed_environment_list.join(' or ')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "failed :thinking: \nusage:`/comment [allowed_environment]`"
            })
            return false

      - name: Stop if invalid
        if: steps.verify-environment.outputs.result === 'false'
        run: exit 1

      - name: Fetch target branch
        id: target-branch
        uses: actions/github-script@v5
        with:
          script: |
            const pull_request = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return {
              url: pull_request.data.html_url,
              state: pull_request.data.state,
              title: pull_request.data.title,
              user: pull_request.data.user.login,
              branch: pull_request.data.head.ref,
              sha: pull_request.data.head.sha,
              base: pull_request.data.base.ref
            }

      - name: Run
        run: echo "${{ fromJSON(steps.target-branch.outputs.result).url }}"

      - name: Finished
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "done :rocket: \nsha:${{fromJSON(steps.target-branch.outputs.result).sha}}"
            })
